### ISSUE TITLE
BBCode tag in same tag

### ISSUE THREAD

**Issue by Typhome** [golonka/BBCodeParser#17]
Hello,

I have problem with BBCode usage.
At first look this: http://prntscr.com/7guyff

BBCode plugin parses only first list (bbcode) and not another list (bbcode) in this list (bbcode).

Same problem with quote.

CKEditor: http://prntscr.com/7guznc
Source code (formatted BBCode): http://pastebin.com/J5M7Npsf

**Comment by golonka** [comment]
Have you tried the latest version?

**Comment by Typhome** [comment]
- Removing golonka/bbcodeparser (v1.3)
  - Installing golonka/bbcodeparser (v2.0.0)
    Downloading: 100%

And it works perfectly, thank you.
