### ISSUE TITLE
Parse [table]

### ISSUE THREAD

**Issue by coderxlsn** [golonka/BBCodeParser#18]
not parse this text

    [table border=1 bgcolor=#99ccff cellspacing=0 width=406 bordercolorlight=#000000 bordercolordark=#666666]<br />
    [tr] <br />
    [td bgcolor=#f0f0f0 colspan=2"] <br />
    [div align=center][font size="2"]<strong> <br />

**Comment by golonka** [comment]
We do not have support for table tags. That why they doesnt get parsed.
