### ISSUE TITLE
There should be a 'parse but remove bbcode' function.

### ISSUE THREAD

**Issue by Admicos** [golonka/BBCodeParser#23]
Can be useful for post previews etc.

example: 
    user types [b]BOLD TEXT[/b]
    without the function: **BOLD TEXT**
    with the function: BOLD TEXT

**Comment by golonka** [comment]
Will work on that.
Do you have any idea of what the syntax should look like?

**Comment by Admicos** [comment]
Maybe like this:
`$bbcode->noFormat('[b]bbcode[/b]')`
