### ISSUE TITLE
BBCode inside [code][/code] tags are parsed.

### ISSUE THREAD

**Issue by Admicos** [golonka/BBCodeParser#25]
Reproducing steps: 
Parse: `[code][color=#0000ff]test[/color][/code]`

Expected: `[color=#0000ff]test[/color]`
Actual: `test`

**Comment by golonka** [comment]
Oops, didn't think about that scenario. This should be fixed.
But I don't really see an easy and clean way to fix this with the way the package is written right know.
Do you have any ideas how to solve this?

**Comment by Admicos** [comment]
I'll try to do some stuff.

**Comment by Admicos** [comment]
I tried some stuff. And it didn't work.

Is there a way to get the current BBCode getting parsed. If not, can you make a way?

**Comment by golonka** [comment]
I have an idea similar to what you did in youtube pull request. Will try that tomorrow.

Probably not the prettiest thing in the world, but hopefully it works.

Work on a better solution for the next major version when we're allowed to break backwards compability.

**Comment by golonka** [comment]
I've tried to find a solution but I can't come up with something that won't break other parts of the package.
Maybe I painted myself into a corner when I wrote the package the way I did.

If this problem would be a deal breaker for anyone the [Decoda package](https://github.com/milesj/decoda) seems to do a nice work handling bbcode inside the code tag.

But if someone finds a solution I will happily merge it!

**Comment by thunderer** [comment]
@golonka @Admicos Please try my Shortcode library, you could easily embed it as an internal parser for your project here: https://github.com/thunderer/Shortcode . It has both regex parsing mechanism which would resolve the reported issues and I also wrote an actual parser that handles any nesting case correctly. I'm now finishing the work on 1.0 release so please use the `dev-master` version, but it's mostly writing better documentation than it is now in README so code should be considered stable. If you'd like it then I could submit a PR here that handles all your BBCodes internally through Shortcode.

**Comment by golonka** [comment]
Fixed by @thunderer in devlop branch. That will later become v3.0.
