### ISSUE TITLE
Only and Except methods don't work as expected in Laravel

### ISSUE THREAD

**Issue by danieliancu** [golonka/BBCodeParser#31]
### Problem

The problem is with the way `only` and `except` methods are handled. They will only work correctly if you new up the class on each use, which doesn't work with the Laravel Facades.

Laravel Facades seem to be cached once resolved, thus the same instance is returned, although the binding with the service provider always returns a new instance.

To reproduce the bug (tested with tinker):

```php
>>> $bbcode = BBCode::only('bold')
=> Golonka\BBCode\BBCodeParser {#871
     +parsers: [
       "bold" => [
         "pattern" => "/\[b\](.*?)\[\/b\]/s",
         "replace" => "<strong>$1</strong>",
         "content" => "$1",
       ],
     ],
   }
```

Unsets all other parsers.

```php
>>> $bbcode->parse('[b]Bold[/b]')
=> "<strong>Bold</strong>"
```

So far so good.

```php
>>> $bbcode = BBCode::only('italic')
=> Golonka\BBCode\BBCodeParser {#871
     +parsers: [],
   }
```

Unsets the remaining `bold` parser.
Note: it's the same object (`#871`) returned above.

```php
>>> $bbcode->parse('[i]Italic[/i]')
=> "[i]Italic[/i]"
```

Of course.

### Solution

1. Implement parsers in a stateless way.
2. Have the Laravel Framework provide a cache option for the facade, so that when it is needed it will always return a new instance (with the help of the service provider).

I tried to find an implementation for the first option, but didn't managed to come up with something worthy.
For the second option, I will write on the chat/forum.

**Comment by golonka** [comment]
Will look into it!

**Comment by danieliancu** [comment]
Wonderful!
Thank you very much for this great package.
