### ISSUE TITLE
Not safe from XSS

### ISSUE THREAD

**Issue by trandaihung** [golonka/BBCodeParser#39]
I've looked at the parser engine, the problem is [IMG] and [Link] tag would not be safe from XSS.

It is very easy just inject javascript into [IMG] and [LINK] tag. So you need to find a better regex than the current one.

**Comment by Antoine-Pous** [comment]
This is your job, this lib is only designed to parse BBCODE tags, not the content.

If you want avoid XSS you must do it yourself before sending data to the parser.

**Comment by golonka** [comment]
I have the same opinion as @Antoine-Pous. 
I see your point, but there are better packages made for just that purpose to sanitize input.

**Comment by trandaihung** [comment]
@Antoine-Pous It seems that you are right, output could be escaped before we send it to the parser. I too focused to the blade template syntax but forget about the php itself. My bad.
